name: Run tutorials

on:
  push:
    branches: [ develop ]
  pull_request:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -e .
        pip install jupyter nbconvert

    - name: Run tutorials
      run: |
        shopt -s globstar nullglob
        jupyter nbconvert --execute --inplace docs/tutorials/**/*.ipynb --ExecutePreprocessor.timeout=600
